const data = {
  products: [
    {
      name: 'Book1',
      slug: 'book-1',
      category: 'Books',
      image: '/images/p1.jpg',
      price: 12,
      countInStock: 10,
      brand: '700',
      rating: 4.5,
      numReviews: 10,
      description: 'interesting book',
    },
    {
      name: 'Book2',
      slug: 'book-2',
      category: 'Books',
      image: '/images/p2.jpg',
      price: 15,
      countInStock: 0,
      brand: '700',
      rating: 4.0,
      numReviews: 10,
      description: 'interesting book',
    },
    {
      name: 'Book3',
      slug: 'book-3',
      category: 'Books',
      image: '/images/p3.jpg',
      price: 20,
      countInStock: 15,
      brand: '700',
      rating: 4.5,
      numReviews: 10,
      description: 'interesting book',
    },
    {
      name: 'Book4',
      slug: 'book-4',
      category: 'Books',
      image: '/images/p4.jpg',
      price: 10,
      countInStock: 5,
      brand: '700',
      rating: 4.5,
      numReviews: 10,
      description: 'interesting book',
    },
  ],
};
export default data;
